<?php
/**
 * Implements hook_form_alter()
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function form_add_form_alter(&$form, &$form_state, $form_id) {


    if($form_id=='page_node_form'){
        dsm($form_id);
        dsm($form);
    }

    $form['title']['#title'] = t('esto es nuevo');
    dsm($form);


    $form['address_field'] = array (
        '#type' => 'textfield',
        '#title' => 'probando',
        '#default_value' => t('write something'),
        '#require' => true,
    );



}

/**
 * Implements hook_menu()
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function form_add_menu(){
	$items['form-add/message'] = array (
		'page callback' => 'greeting_text',
		'access callback' => TRUE,
		'title' => 'Welcome to drupal world',
	);
	return $items;
}

function greeting_text(){
	return "Hola Mundo";
}
