<?php
/**
 * Implements hook_menu()
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function form_add_form_alter(&$form, &$form_state, $form_id) {


    if($form_id=='page_node_form'){
        dsm($form_id);
        dsm($form);
    }

    $form['title']['#title'] = t('esto es nuevo');
    dsm($form);


    $form['address_field'] = array (
        '#type' => 'textfield',
        '#title' => 'probando',
        '#default_value' => t('write something'),
        '#require' => true,
    );



}